---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 13

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt]
  - name: centos-6

suites:
  - name: default
    run_list:
      - recipe[test::default]
    verifier:
      inspec_tests:
        - test/smoke/default
  - name: ulimit
    run_list:
      - recipe[test::default]
    verifier:
      inspec_tests:
        - test/smoke/ulimit
    attributes:
      stunnel:
        ulimit: 8192
  - name: certificates
    run_list:
      - recipe[test::certificates]
    verifier:
      inspec_tests:
        - test/smoke/certificates
  - name: source
    run_list:
      - recipe[test::default]
    verifier:
      inspec_tests:
        - test/smoke/source
    attributes:
      install_method: 'source'
