---
driver:
  name: vagrant
  vagrantfile_erb: Vagrantfile.erb

provisioner:
  name: chef_zero

verifier:
  name: inspec
  format: doc
  
platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[stunnel_test::default]
  - name: certificates
    run_list:
      - recipe[stunnel_test::certificates]
  - name: source
    run_list:
      - recipe[stunnel_test::default]
    attributes:
      install_method: 'source'
