---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt]
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[test_stunnel::default]
  - name: ulimit
    run_list:
      - recipe[test_stunnel::default]
    attributes:
      stunnel:
        ulimit: 8192
  - name: certificates
    run_list:
      - recipe[test_stunnel::certificates]
  - name: source
    run_list:
      - recipe[test_stunnel::default]
    attributes:
      install_method: 'source'
