---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 13

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: centos-6
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[test::default]
    verifier:
      inspec_tests:
        - test/smoke/default
  - name: ulimit
    run_list:
      - recipe[test::default]
    verifier:
      inspec_tests:
        - test/smoke/ulimit
    attributes:
      stunnel:
        ulimit: 8192
  - name: certificates
    run_list:
      - recipe[test::certificates]
    verifier:
      inspec_tests:
        - test/smoke/certificates
