sudo: required
dist: trusty
services: docker

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

env:
  global:
  - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml

env:
  matrix:
  - KITCHEN_REGEXP=default
  - KITCHEN_REGEXP=certificates

# Don't `bundle install` because we're using ChefDK
install: echo "skip bundle install"

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

before_script:
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - chef gem install kitchen-dokken
  - chef gem install stove

script:
  - chef exec delivery local all
  - kitchen verify ${KITCHEN_REGEXP} -c 2

notifications:
  email: false
  slack:
    secure: T/NjVX3wPLQeMp4n6fiwBW3dhDIH0WIklH16cfUugPm8IlDRA+4+hQxUmqEOBse9dPu2NPcirZnXxiAmk5W1qUvNdsSBLKQ8NF6ahNITQBiQPpjfKuv1XY9SYijtEGN340fbSha2k7IRXzxleJySiQdo+KbFfDvZnpeGACb/rdE=
