---
jobs:
  final:
    docker:
      - image: bash:latest
    steps:
      - run:
          name: Finish cooking
          command: echo "Finished cooking"
lint_and_unit: &lint_and_unit
  - delivery
  - danger
  - lint-yaml
  - lint-markdown
version: 2.1
orbs:
  kitchen: sous-chefs/kitchen@2
workflows:
  kitchen:
    jobs:
      - kitchen/yamllint:
          name: lint-yaml
      - kitchen/mdlint:
          name: lint-markdown
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/delivery:
          name: delivery
      - kitchen/dokken-single:
          name: default-debian-8
          suite: default-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: default-debian-9
          suite: default-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: default-centos-6
          suite: default-centos-6
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: default-centos-7
          suite: default-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: default-ubuntu-1604
          suite: default-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: default-ubuntu-1804
          suite: default-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: default-amazonlinux-2
          suite: default-amazonlinux-2
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: ulimit-debian-8
          suite: ulimit-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: ulimit-debian-9
          suite: ulimit-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: ulimit-centos-6
          suite: ulimit-centos-6
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: ulimit-centos-7
          suite: ulimit-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: ulimit-ubuntu-1604
          suite: ulimit-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: ulimit-ubuntu-1804
          suite: ulimit-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: ulimit-amazonlinux-2
          suite: ulimit-amazonlinux-2
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: certificates-debian-8
          suite: certificates-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: certificates-debian-9
          suite: certificates-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: certificates-centos-6
          suite: certificates-centos-6
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: certificates-centos-7
          suite: certificates-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: certificates-ubuntu-1604
          suite: certificates-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: certificates-ubuntu-1804
          suite: certificates-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: certificates-amazonlinux-2
          suite: certificates-amazonlinux-2
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: source-debian-8
          suite: source-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: source-debian-9
          suite: source-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: source-centos-6
          suite: source-centos-6
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: source-centos-7
          suite: source-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: source-ubuntu-1604
          suite: source-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: source-ubuntu-1804
          suite: source-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: source-amazonlinux-2
          suite: source-amazonlinux-2
          requires: *lint_and_unit
      - final:
          requires:
            - default-debian-8
            - default-debian-9
            - default-centos-6
            - default-centos-7
            - default-ubuntu-1604
            - default-ubuntu-1804
            - default-amazonlinux-2
            - ulimit-debian-8
            - ulimit-debian-9
            - ulimit-centos-6
            - ulimit-centos-7
            - ulimit-ubuntu-1604
            - ulimit-ubuntu-1804
            - ulimit-amazonlinux-2
            - certificates-debian-8
            - certificates-debian-9
            - certificates-centos-6
            - certificates-centos-7
            - certificates-ubuntu-1604
            - certificates-ubuntu-1804
            - certificates-amazonlinux-2
            - source-debian-8
            - source-debian-9
            - source-centos-6
            - source-centos-7
            - source-ubuntu-1604
            - source-ubuntu-1804
            - source-amazonlinux-2
