---
lint_and_unit: &lint_and_unit
  - delivery
  - danger
  - lint-yaml
  - lint-markdown
version: 2.1
orbs:
  kitchen: sous-chefs/kitchen@2
workflows:
  kitchen:
    jobs:
      - kitchen/yamllint:
          name: lint-yaml
      - kitchen/mdlint:
          name: lint-markdown
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/delivery:
          name: delivery
      - kitchen/dokken-single:
          name: default-amazon-linux
          suite: default-amazon-linux
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: default-amazon-linux-2
          suite: default-amazon-linux-2
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: default-centos-6
          suite: default-centos-6
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: default-centos-7
          suite: default-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: default-debian-8
          suite: default-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: default-debian-9
          suite: default-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: default-fedora-latest
          suite: default-fedora-latest
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: default-opensuse-leap-15
          suite: default-opensuse-leap-15
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: default-ubuntu-1604
          suite: default-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: default-ubuntu-1804
          suite: default-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: ulimit-amazon-linux
          suite: ulimit-amazon-linux
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: ulimit-amazon-linux-2
          suite: ulimit-amazon-linux-2
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: ulimit-centos-6
          suite: ulimit-centos-6
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: ulimit-centos-7
          suite: ulimit-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: ulimit-debian-8
          suite: ulimit-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: ulimit-debian-9
          suite: ulimit-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: ulimit-fedora-latest
          suite: ulimit-fedora-latest
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: ulimit-opensuse-leap-15
          suite: ulimit-opensuse-leap-15
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: ulimit-ubuntu-1604
          suite: ulimit-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: ulimit-ubuntu-1804
          suite: ulimit-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: certificates-amazon-linux
          suite: certificates-amazon-linux
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: certificates-amazon-linux-2
          suite: certificates-amazon-linux-2
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: certificates-centos-6
          suite: certificates-centos-6
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: certificates-centos-7
          suite: certificates-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: certificates-debian-8
          suite: certificates-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: certificates-debian-9
          suite: certificates-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: certificates-fedora-latest
          suite: certificates-fedora-latest
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: certificates-opensuse-leap-15
          suite: certificates-opensuse-leap-15
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: certificates-ubuntu-1604
          suite: certificates-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: certificates-ubuntu-1804
          suite: certificates-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: source-amazon-linux
          suite: source-amazon-linux
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: source-amazon-linux-2
          suite: source-amazon-linux-2
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: source-centos-6
          suite: source-centos-6
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: source-centos-7
          suite: source-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: source-debian-8
          suite: source-debian-8
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: source-debian-9
          suite: source-debian-9
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: source-fedora-latest
          suite: source-fedora-latest
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: source-opensuse-leap-15
          suite: source-opensuse-leap-15
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: source-ubuntu-1604
          suite: source-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: source-ubuntu-1804
          suite: source-ubuntu-1804
          requires: *lint_and_unit
