version: 2.1

orbs:
  kitchen: sous-chefs/kitchen@1.0.0

workflows:
  kitchen:
    jobs:
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/lint:
          name: lint
      - kitchen/dokken:
          name: source-18
          suite: source-18
          requires: [danger, lint]
      - kitchen/dokken:
          name: default
          suite: default
          requires: [danger,lint]
      - kitchen/dokken:
          name: ulimit
          suite: ulimit
          requires: [danger,lint]
      - kitchen/dokken:
          name: certificates
          suite: certificates
          requires: [danger,lint]
      - kitchen/dokken:
          name: source
          suite: source
          requires: [danger,lint]
