version: 2
jobs:
  build:
    parallelism: 2
    dependencies:
      pre:
        - curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -c stable -P chefdk
    docker:
      - image: circleci/ruby:2.4
    steps:
      - checkout
      - run:
          name: load chefdk
          command: |
            eval "$(/opt/chefdk/bin/chef shell-init bash)"
      - run:
          name: gem installs
          command: |
            chef gem install kitchen-dokken
            chef gem install stove
      - run:
          name: lint and unit
          command: |
            chef exec delivery local all
      - run:
          name: test
          environment:
            KITCHEN_LOCAL_YAML: .kitchen.dokken.yml
          command: |
            kitchen test default-ubuntu-1404
